package regex.enumType;

/**
 * Enum com os nomes de todas as regras utilizadas pelo tradutor.
 */
public enum RegraRegex {
	MULTIPLE, SUB_EXPRESSION, GROUP, START_ANCHOR, END_ANCHOR, ONE_OR_MORE,
	ZERO_OR_MORE, CONDITIONAL, EXACT, AT_LEAST, BETWEEN, NEGATIVE_LIST,
	POSITIVE_LIST, LIST_NO_SPECIAL, LIST_FIRST_RANGE, LIST_LAST_ELEMENT,
	RANGE, LIST_CHARACTER, ALNUM, ALPHA, BLANK, CNTRL, DIGIT_CLASS, GRAPH,
	LOWER, PRINT, PUNCT, UPPER, X_DIGIT, ANY_CHAR, CHARACTERS, CHARACTER,
	SPACE_CLASS
}
